# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CSDNModuleExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CSDNModuleExample
  pod 'CSDNModuleExample', :path => './'
  
  target 'CSDNModuleExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSDNModuleExampleUITests' do
    # Pods for testing
  end

end
